version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/recipes.db:/app/recipes.db
    env_file:
      - ./backend/.env.example
    environment:
      - DATABASE_URL=postgresql://neondb_owner:npg_uX6figY4Knob@ep-crimson-math-akrqdohx-pooler.c-3.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - DB_SSL=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
