services:
  - type: web
    name: recipe-manager
    env: docker
    plan: free
    region: oregon
    healthCheckPath: /api/v1/recipes/public
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: "*"
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 465
      - key: MAIL_USERNAME
        value: mahimadangi78@gmail.com
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_FROM
        value: mahimadangi78@gmail.com
      - key: MAIL_STARTTLS
        value: "false"
      - key: MAIL_SSL_TLS
        value: "true"
      - key: PORT
        value: 10000
